import type { Metadata } from "next";
import "../../styles/globals.css";
import { IBM_Plex_Serif } from 'next/font/google'
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Navbar } from "../components/Navbar";
import { fetchApi } from "@/lib/fetchApi";

export const metadata: Metadata = {
  title: "Event Pro Gran Canaria",
  description: "Generated by create next app",
};

const ibmPlexSerif = IBM_Plex_Serif({
  weight: '400',
  subsets: ['latin'],
})


export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const [{ items }]:any = await fetchApi({
    apiRoute: '/api/tree-menus/menu',
    locale,
    filters: {
      documentId: {
        $eq: 'wan65cr54i0uzw1doz6qv703',
      },
    },
  });


  return (
    <html lang={locale}>
      <body className={ibmPlexSerif.className}>
        <NextIntlClientProvider>
          <Navbar data={items} />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
